---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: example-1 # Use this field to overwrite namespace for the manifests
resources:
  - "../../../base/pacman/"

# Patch the application to change the cluster specific details
patches:
- path: patch-pacman.yaml
  target:
    kind: Deployment
    name: pacman
    version: v1

- path: patch-mongo.yaml
  target:
    kind: Deployment
    name: mongo
    version: v1

- path: patch-mongo-storage.yaml
  target:
    kind: PersistentVolumeClaim
    name: mongo-storage
    version: v1
